name: Schedule > Approve > 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  bot:
    name: Bot
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Bot
        uses: liblaf/actions/approve@v1
        with:
          approve-token: ${{ secrets.GH_PAT }}
          bot: true
          labels: bot
          repository: ${{ github.repository_owner }}

  pre-commit-ci:
    name: pre-commit.ci
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve pre-commit-ci[bot]
        uses: liblaf/actions/approve@v1
        with:
          approve-token: ${{ secrets.GH_PAT }}
          authors: pre-commit-ci[bot]
          bot: true
          repository: ${{ github.repository_owner }}
