name: Schedule > Approve > Weekly

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00, only on Sunday
  workflow_dispatch:

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Release Please
        uses: liblaf/actions/approve@dist
        with:
          approve-token: ${{ secrets.GH_PAT }}
          bot: true
          labels: "autorelease: pending"
          repository: ${{ github.repository_owner }}
